<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>workflow-test</artifactId>
    <version>${revision}</version>

    <properties>
        <revision>0.4.0</revision>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>3.6.2</version>
                <executions>
                    <execution>
                        <id>master</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <phase>none</phase>
                        <configuration>
                            <rules>
                                <requireProperty>
                                    <property>revision</property>
                                    <message>Property 'revision' is required.</message>
                                    <regex>^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)</regex>
                                    <regexMessage>Property 'revision' needs to match Semantic Versioning 2.0.0 pattern.</regexMessage>
                                </requireProperty>
                            </rules>
                        </configuration>
                    </execution>
                    <execution>
                        <id>develop</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <phase>none</phase>
                        <configuration>
                            <rules>
                                <requireProperty>
                                    <property>revision</property>
                                    <message>Property 'revision' is required.</message>
                                    <regex>develop-SNAPSHOT</regex>
                                    <regexMessage>Property 'revision' needs to be equal to 'develop-SNAPSHOT'.</regexMessage>
                                </requireProperty>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
